language: node_js
node_js:
  - "6.2.2"
before_install:
  - "npm install -g bower"
  - "bower install"
  - "npm install -g polymer-cli"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
script: "polymer test -l firefox"
